export const SET_QUERY_ROUTE = "SET_QUERY_ROUTE";
export const CLEAR_QUERY_ROUTE = "CLEAR_QUERY_ROUTE";
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const SET_BOOKING = "SET_BOOKING";
export const CLEAR_BOOKING = "CLEAR_BOOKING";
export const SET_SELECTED_SEAT = "SET_SELECTED_SEAT";
export const REMOVE_SELECTED_SEAT = "REMOVE_SELECTED_SEAT";
export const CLEAR_SELECTED_SEAT = "CLEAR_SELECTED_SEAT";
export const SET_SELECTED_ROUTE = "SET_SELECTED_ROUTE";
// AUTH
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
