export const SET_QUERY_ROUTE = "SET_QUERY_ROUTE";
export const CLEAR_QUERY_ROUTE = "CLEAR_QUERY_ROUTE";
export const SET_SELECTED_SEAT = "SET_SELECTED_SEAT";
export const CLEAR_SELECTED_SEAT = "CLEAR_SELECTED_SEAT";
export const REMOVE_SELECTED_SEAT = "REMOVE_SELECTED_SEAT";
